# Generated by Django 5.2.17 on 2026-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_url_alter_project_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituion', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
