# Generated by Django 5.2.17 on 2026-09-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_remove_experience_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='instituion',
            new_name='institution',
        ),
    ]
